Document: forensic-vm
Title: Debian forensic-vm Manual
Author: <insert document author here>
Abstract: This manual describes what forensic-vm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/forensic-vm/forensic-vm.sgml.gz

Format: postscript
Files: /usr/share/doc/forensic-vm/forensic-vm.ps.gz

Format: text
Files: /usr/share/doc/forensic-vm/forensic-vm.text.gz

Format: HTML
Index: /usr/share/doc/forensic-vm/html/index.html
Files: /usr/share/doc/forensic-vm/html/*.html
