# Generated by Django 4.1.9 on 2023-10-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0006_chainofcustody_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainofcustody',
            name='uuid',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
