# Generated by Django 4.1.9 on 2023-10-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0007_chainofcustody_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=36)),
                ('conversion_time_txt', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('image_type', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
                ('conversion_time_in_seconds', models.FloatField()),
                ('disk_read', models.FloatField()),
                ('disk_write', models.FloatField()),
                ('elapsed_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('image_size', models.FloatField()),
                ('start_time', models.FloatField()),
                ('transfer_read_speed', models.FloatField()),
                ('distro', models.CharField(default='---', max_length=100)),
                ('hostname', models.CharField(default='---', max_length=100)),
                ('osinfo', models.CharField(default='---', max_length=100)),
                ('product_name', models.CharField(default='---', max_length=100)),
            ],
        ),
    ]
