# Generated by Django 4.1.9 on 2023-10-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0008_vmdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmdata',
            name='end_time_full',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='vmdata',
            name='start_time_full',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='distro',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='hostname',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='osinfo',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='product_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
