# Generated by Django 4.1.9 on 2023-10-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0010_vmdata_booted_vmdata_first_boot_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmdata',
            name='booted',
            field=models.BooleanField(default=False),
        ),
    ]
