# Generated by Django 4.1.9 on 2023-10-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0011_alter_vmdata_booted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmdata',
            name='image_real_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='vmdata',
            name='image_source',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
