# Generated by Django 4.1.9 on 2023-10-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0012_vmdata_image_real_name_vmdata_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmdata',
            name='image_description',
            field=models.TextField(default='N/A'),
        ),
    ]
