# Generated by Django 4.1.9 on 2023-10-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0013_vmdata_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmdata',
            name='booted',
            field=models.BooleanField(default=False, verbose_name='If OS Booted - Manual check'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='conversion_time_in_seconds',
            field=models.FloatField(verbose_name='Real conversion time in seconds'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='conversion_time_txt',
            field=models.CharField(max_length=255, verbose_name='Conversion time: HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='disk_read',
            field=models.FloatField(verbose_name='Disk read test in MB/s'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='disk_write',
            field=models.FloatField(verbose_name='Disk write test in MB/s'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='distro',
            field=models.CharField(default='N/A', max_length=100, verbose_name='OS Distribution'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='elapsed_time',
            field=models.FloatField(verbose_name='Elapsed time in ticks'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='end_time',
            field=models.FloatField(verbose_name='End time in ticks'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='end_time_full',
            field=models.CharField(default='N/A', max_length=100, verbose_name='End time date'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='extension',
            field=models.CharField(max_length=10, verbose_name='Disk image extension'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='Disk image filename'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='first_boot_time',
            field=models.FloatField(default=0, verbose_name='First boot time - Manual check'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='hostname',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='image_description',
            field=models.TextField(default='N/A', verbose_name='Image site description'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='image_real_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Image site identification'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='image_size',
            field=models.FloatField(verbose_name='Image size in bytes'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='image_source',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Image site source'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='image_type',
            field=models.CharField(max_length=50, verbose_name='Tool used to mount image'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='mode',
            field=models.CharField(max_length=50, verbose_name='Conversion mode'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='osinfo',
            field=models.CharField(default='N/A', max_length=100, verbose_name='OS Info'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='product_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name='OS product name'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='real_image_type',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Real image type'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='start_time',
            field=models.FloatField(verbose_name='Start time in ticks'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='start_time_full',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Start time date'),
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='transfer_read_speed',
            field=models.FloatField(verbose_name='Network image read test in MB/s'),
        ),
    ]
