# Generated by Django 4.1.9 on 2023-10-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0014_alter_vmdata_booted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vmdata',
            options={'verbose_name': 'Metrics'},
        ),
        migrations.AlterField(
            model_name='vmdata',
            name='real_image_type',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('VMDK', 'VMDK'), ('ENCASE', 'Encase'), ('AFF', 'AFF'), ('RAW', 'RAW'), ('SMART', 'SMART')], default='N/A', max_length=10, verbose_name='Real image type'),
        ),
    ]
