# Generated by Django 4.1.9 on 2023-10-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0015_alter_vmdata_options_alter_vmdata_real_image_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vmdata',
            options={'verbose_name': 'Metric'},
        ),
    ]
