# Generated by Django 4.1.9 on 2023-10-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0016_alter_vmdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainofcustody',
            name='ip_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
