# Generated by Django 4.1.9 on 2023-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0017_chainofcustody_ip_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmdata',
            name='real_image_type',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('VMDK', 'VMDK'), ('ENCASE', 'Encase'), ('AFF', 'AFF'), ('RAW', 'RAW'), ('SMART', 'SMART'), ('QCOW2', 'QCOW2')], default='N/A', max_length=10, verbose_name='Real image type'),
        ),
    ]
